### ISSUE TITLE
Error: Call to a member function setPreference() on null

### ISSUE THREAD

**Issue by hlorofos** [derekmd/laravel-dusk-firefox#14]
I've got laradock container with Firefox installed
```
firefox --version
Mozilla Firefox 90.0
```

`php artisan dusk:install-firefox`
also ran with
```
Firefox scaffolding installed successfully.
Downloading Geckodriver binaries...
Geckodriver binary successfully installed for version v0.29.1.
```
however I'm getting 

`Error: Call to a member function setPreference() on null`
from the following code
```
        $capabilities->getCapability(FirefoxDriver::PROFILE)
            ->setPreference('devtools.console.stdout.content', true);
```

**Comment by derekmd** [comment]
It looks like the "php-webdriver/webdriver" package (a dependency of Laravel Dusk) introduced a breaking change by no longer setting up the Firefox profile starting in v1.11.0 (a _minor_ release?): https://github.com/php-webdriver/php-webdriver/pull/890/files#diff-ffbfd51f39f3064af75d9fea1b50bbcde91fdd03aa429a7101c4416d1b43d802L299

Four potential solutions for now:

1. You can remove these lines:

   ```
   $capabilities->getCapability(FirefoxDriver::PROFILE)
       ->setPreference('devtools.console.stdout.content', true);
   ```

   If you don't care about debug feedback on JavaScript errors printed to the browser console.
2. Use Composer to downgrade package "php-webdriver/webdriver" to v1.10.0
3. Copy some of that old "php-webdriver/webdriver" code into your tests/DuskTestCase.php file. Add imports:

   ```php
   import Facebook\WebDriver\Firefox\FirefoxProfile;
   import Facebook\WebDriver\Firefox\FirefoxPreferences;
   ```
   
   and replace:

   ```php
   $capabilities->getCapability(FirefoxDriver::PROFILE)
       ->setPreference('devtools.console.stdout.content', true);
   ```
   
   with:
   
   ```php
   $capabilities->setCapability(
       FirefoxDriver::PROFILE,
       (new FirefoxProfile)
           ->setPreference(FirefoxPreferences::READER_PARSE_ON_LOAD_ENABLED, false);
           ->setPreference(FirefoxPreferences::DEVTOOLS_JSONVIEW, false)
           ->setPreference('devtools.console.stdout.content', true)
   );
   ```
4. When I find time I'll have to update this package's stubs to make the command `php artisan dusk:install-firefox` again generate a working `DuskTestCase.php` file. There's apparently a new `FirefoxOptions` class now used for configuration. This is the fun/nightmare of open source ecosystems with a single weak link.

**Comment by derekmd** [comment]
Composer update "derekmd/laravel-dusk-firefox" to v1.6.1 released just now, re-run `php artisan dusk:install-firefox`, and your Laravel Dusk test suite should now run in Firefox.

**Comment by hlorofos** [comment]
Awesome, thanks for the quick turnaround!
