### ISSUE TITLE
How to increase timeout?

### ISSUE THREAD

**Issue by shemgp** [derekmd/laravel-dusk-firefox#17]
I'm getting:
```
Facebook\WebDriver\Exception\TimeoutException: Timeout loading page after 300000ms
```
in my slow work from home machine, but I already increased the timeout via `::create`:
```php
        return RemoteWebDriver::create(
            $_ENV['DUSK_DRIVER_URL'] ?? 'http://localhost:4444',
            $capabilities,
            9000000, 9000000
        );
```

Thanks for your work on this package. I switched to it since chrome has a bug where rendering timeouts occur.

**Comment by derekmd** [comment]
I'm assuming that 5 minute timeout value is a Geckodriver/Firefox hardcoded value independent of the other timeout parameters passed into `RemoteWebDriver::create()`. So arguments `$connection_timeout_in_ms` and `$request_timeout_in_ms` always must be _below_ integer `300000`.

For support you probably want to try the Laravel community forums that cover Laravel Dusk:

* https://laravel.io/forum/tags/dusk?filter=recent
* https://laracasts.com/discuss/channels/testing

I really don't know much about timeout problem other than [choosing the wait time for specific DOM selectors](https://laravel.com/docs/dusk#waiting-for-selectors). If the HTTP request fails to return a response, ensure `php artisan serve` or a Apache httpd instance are running before executing `php artisan dusk`.

This is more a general inquiry how Laravel Dusk and the web driver API interact so for research you can have a look at reports within the package dependencies about timeout errors:

* https://github.com/laravel/dusk/issues?q=is%3Aissue+timeout
* https://github.com/php-webdriver/php-webdriver/issues?q=is%3Aissue+"TimeoutException"
* https://github.com/mozilla/geckodriver/issues?q=is%3Aissue+%22Timeout+loading+page+after%22

> in my slow work from home machine
> since chrome has a bug where rendering timeouts occur

This is an obvious answer, but you may simply need a hardware upgrade although I can run Laravel Dusk without issue on a decade-old laptop using either Chromedriver or Geckodriver. It's unfortunate but modern web development has more demanding requirements.
