### ISSUE TITLE
Impossible to pass arguments to startChromeDriver function

### ISSUE THREAD

**Issue by lk77** [derekmd/laravel-dusk-firefox#24]
Hello,

it's impossible to pass arguments to chrome driver function, without loosing dusk:chrome driver, 
because it triggers the following message :

```
It looks like you must configure your application for Chromedriver.
Run "php artisan dusk:install-firefox --with-chrome" to install new scaffolding.
```

it's because of this function :

```
protected function hasChromedriverSetup()
{
    return Str::contains($this->duskTestCaseContents(), 'startChromeDriver()');
}
```

which check for the string startChromeDriver()

it's possible to bypass the check by doing :

```
static::startChromeDriver(['--port=9515']);//startChromeDriver()
```

but it's not very clean

**Comment by derekmd** [comment]
1. The `startChromeDriver()` substring inspection would need to be changed to a regex pattern so arguments can be passed in the stub's application copy. I may change the phrase to another "chrome" substring that's always present in both `vendor/derekmd/laravel-dusk-firefox/stubs/DuskTestCase.stub` and `vendor/laravel/dusk/stubs/DuskTestCase.stub`.
2. `ChromeCommand` could also use a bypass option such as `--skip-install-check`.
