### ISSUE TITLE
Bug: ssl certificate

### ISSUE THREAD

**Issue by SkyperHH** [derekmd/laravel-dusk-firefox#29]
After the execution of: php artisan dusk:install-firefox
the following error is displayed:

Downloading Geckodriver binaries...
Failed to download https://api.github.com/repos/mozilla/geckodriver/releases/latest: cURL error 60: SSL certificate problem: unable to get local issuer certificate (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://api.github.com/repos/mozilla/geckodriver/releases/latest

The execution is then aborted.

**Comment by derekmd** [comment]
Use command line option `--ssl-no-verify` to skip cURL certificate verification on domain `https://github.com` or follow the instructions I've added to the FAQ to configure php.ini for the OpenSSL extension: https://github.com/derekmd/laravel-dusk-firefox#faq
