### ISSUE TITLE
Geckodrivers Missing for Mac and Linux

### ISSUE THREAD

**Issue by jrquick17** [derekmd/laravel-dusk-firefox#7]
I ran the following in my Laravel 6/PHP 7.3 project on Mac OS:

% php artisan dusk:install-firefox
 Overwrite file /Users/jrquick/development/uabshp/r3/laravel/tests/DuskTestCase.php? (yes/no) [no]:
 > yes

Firefox scaffolding installed successfully.
Downloading Geckodriver binaries...
Geckodriver binary successfully installed for version v0.29.0.

% php artisan dusk:firefox-driver --all                                                                                
x geckodriver
Unable to find executable in downloaded file /Users/jrquick/development/uabshp/r3/laravel/vendor/derekmd/laravel-dusk-firefox/src/Console/../../bin/geckodriver-v0.29.0-linux64.tar.gz
x geckodriver
Unable to find executable in downloaded file /Users/jrquick/development/uabshp/r3/laravel/vendor/derekmd/laravel-dusk-firefox/src/Console/../../bin/geckodriver-v0.29.0-macos.tar.gz

Seems to be missing linux and max geckodrivers

**Comment by tpaksu** [comment]
You can manually download them from here and add them to `bin` folder. But there's a catch, the mac driver should be renamed to `geckodriver-mac` after you download it. (It seems the package searchs for that name in that folder)
